import { VercelRequest, VercelResponse } from '@vercel/node';
import { Resend } from 'resend';

// Initialize resilient error handling for missing API keys in local dev vs. prod
const apiKey = process.env.RESEND_API_KEY || '';
const resend = new Resend(apiKey);

export default async function handler(req: VercelRequest, res: VercelResponse) {
  // CORS check
  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  // Only allow POST requests from the front-end form
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  const {
    fullName,
    email,
    phone,
    address,
    residenceType,
    fencedYard,
    hoursAlone,
    currentPets,
    frenchieExperience,
    vetName,
    vetPhone,
    intent,
    rawFeeding,
    heatAcknowledgment,
    priceAcknowledgment,
    message
  } = req.body;

  try {
    if (!apiKey) {
      console.warn("RESEND_API_KEY is not defined in the environment.");
      // We will pretend to succeed for local testing if the key doesn't exist
      return res.status(200).json({ success: true, message: "Simulated email send (No API Key)" });
    }

    const htmlBody = `
      <div style="font-family: sans-serif; max-w-4xl; margin: auto; padding: 20px; color: #1e293b; background: white;">
        <h1 style="color: #0d9488; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px;">New Breeder Application</h1>
        
        <h2 style="color: #475569; margin-top: 30px;">1. Contact Details</h2>
        <table style="width: 100%; text-align: left; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0; width: 150px;">Name</th><td>${fullName}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Email</th><td><a href="mailto:${email}">${email}</a></td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Phone</th><td>${phone}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Location</th><td>${address}</td></tr>
        </table>

        <h2 style="color: #475569; margin-top: 30px;">2. Living Environment</h2>
        <table style="width: 100%; text-align: left; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0; width: 150px;">Residence Type</th><td>${residenceType}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Fenced Yard?</th><td>${fencedYard}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Hours Alone/Day</th><td>${hoursAlone} hrs</td></tr>
        </table>

        <h2 style="color: #475569; margin-top: 30px;">3. Experience & References</h2>
        <table style="width: 100%; text-align: left; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0; width: 150px;">Current Pets</th><td>${currentPets}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Frenchie History</th><td>${frenchieExperience}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Veterinarian Name</th><td>${vetName}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Veterinarian Phone</th><td>${vetPhone}</td></tr>
        </table>

        <h2 style="color: #475569; margin-top: 30px;">4. Intent & Agreements</h2>
        <table style="width: 100%; text-align: left; border-collapse: collapse;">
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0; width: 150px;">Purpose</th><td>${intent}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Raw Diet OK?</th><td>${rawFeeding}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Acknowledges Heat Risk</th><td>${heatAcknowledgment ? 'Yes' : 'No'}</td></tr>
            <tr style="border-bottom: 1px solid #f1f5f9;"><th style="padding: 8px 0;">Acknowledges Pricing</th><td>${priceAcknowledgment ? 'Yes' : 'No'}</td></tr>
        </table>

        <h2 style="color: #475569; margin-top: 30px;">5. Personal Message</h2>
        <p style="background: #f8fafc; padding: 15px; border-left: 4px solid #0d9488; font-style: italic;">
          ${message || 'No additional message provided.'}
        </p>

        <p style="margin-top: 40px; font-size: 12px; color: #94a3b8; text-align: center;">
            This email was automatically generated by the OKC Frenchies Breeder Application via Resend.
        </p>
      </div>
    `;

    // Send via Resend
    const data = await resend.emails.send({
      from: 'OKC Frenchies Applications <onboarding@resend.dev>', // Usually you use onboarding@resend.dev until custom domain verified
      to: ['info@okcfrenchies.com'], 
      replyTo: email,
      subject: `BREEDER APP: ${fullName} (${intent})`,
      html: htmlBody
    });

    return res.status(200).json({ success: true, data });
  } catch (error: any) {
    console.error("Resend delivery failed:", error);
    return res.status(500).json({ error: error.message });
  }
}
